name: Build and Test Java Pipeline

pr:
- master
- develop

trigger: none

strategy:
  matrix:
    linux-JDK8:
      imageName: 'ubuntu-latest'
      jdkVersion: '1.8'
    linux-JDK11:
      imageName: 'ubuntu-latest'
      jdkVersion: '1.11'
    mac-JDK8:
      imageName: 'macos-latest'
      jdkVersion: '1.8'
    mac-JDK11:
      imageName: 'macos-latest'
      jdkVersion: '1.11'
    windows-JDK8:
      imageName: 'windows-latest'
      jdkVersion: '1.8'
    windows-JDK11:
      imageName: 'windows-latest'
      jdkVersion: '1.11'


pool:
  vmImage: $(imageName)

steps:

- checkout: self
  submodules: recursive
  lfs: true
  persistCredentials: true

- task: Maven@1
  displayName: 'Maven test'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dhttps.protocols=TLSv1.2 -DfailIfNoTests=false -DXmx2048m'
    jdkVersionOption: $(jdkVersion)
    testRunTitle: '$(imageName)-$(jdkVersion)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'