name: Build and Test Java Pipeline

pr:
- master
- develop

trigger: none

stages:

- stage: Build_Windows
  dependsOn: []
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    steps:

    - checkout: self
      submodules: recursive
      lfs: true
      persistCredentials: true

    - task: Maven@1
      displayName: 'Maven test'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean test'
        options: '-Dhttps.protocols=TLSv1.2 -DfailIfNoTests=false -DXmx2048m'
        jdkVersionOption: '1.7'
        testRunTitle: 'Windows'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        
- stage: Build_Mac
  dependsOn: []
  jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'

    steps:

    - checkout: self
      submodules: recursive
      lfs: true

    - task: Maven@1
      displayName: 'Maven test'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean test'
        options: '-Dhttps.protocols=TLSv1.2 -DfailIfNoTests=false -DXmx2048m'
        jdkVersionOption: '1.7'
        testRunTitle: 'Mac'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: Build_Linux
  dependsOn: []
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - checkout: self
      submodules: recursive
      lfs: true

    - task: Maven@1
      displayName: 'Maven test'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean test'
        options: '-Dhttps.protocols=TLSv1.2 -DfailIfNoTests=false -DXmx2048m'
        jdkVersionOption: '1.7'
        testRunTitle: 'Linux'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'