name: Nigthly Submodule Update

on:
  workflow_dispatch:

jobs:   

  call-workflow-nightly-submodule-update:
    uses: 51Degrees/common-ci/.github/workflows/nightly-submodule-update.yml@main
    with:
      repo-name: "actions-testing"
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
