name: Pull Requests

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
      common-ci-ref:
        type: string
        description: "common-ci branch/tag/sha to use (default: main)"
        default: ''

jobs:
  PullRequests:
    name: Pull Requests
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      common-ci-ref: ${{ inputs.common-ci-ref }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
